export const SAFE_ROUTE_LOCATIONS = {
  AT: ["Vienna", "Salzburg", "Graz", "Linz", "Innsbruck"],
  AU: ["Sydney", "Melbourne", "Brisbane", "Perth", "Adelaide", "Canberra", "Hobart"],
  BE: ["Brussels", "Antwerp", "Ghent", "Bruges", "Liege"],
  BR: ["Sao Paulo", "Rio de Janeiro", "Brasilia", "Salvador", "Fortaleza", "Porto Alegre"],
  CA: ["Toronto", "Vancouver", "Montreal", "Calgary", "Ottawa", "Edmonton", "Winnipeg", "Halifax"],
  CH: ["Zurich", "Geneva", "Basel", "Bern", "Lausanne", "Lucerne"],
  CZ: ["Prague", "Brno", "Ostrava", "Plzen", "Liberec"],
  DE: ["Berlin", "Hamburg", "Munich", "Cologne", "Frankfurt", "Stuttgart", "Leipzig", "Dortmund"],
  DK: ["Copenhagen", "Aarhus", "Odense", "Aalborg", "Esbjerg"],
  ES: ["Madrid", "Barcelona", "Valencia", "Seville", "Malaga", "Bilbao", "Zaragoza", "Palma"],
  FI: ["Helsinki", "Espoo", "Tampere", "Turku", "Oulu", "Vantaa", "Jyvaskyla", "Kuopio", "Lahti", "Joensuu"],
  FR: ["Paris", "Marseille", "Lyon", "Toulouse", "Nice", "Nantes", "Lille", "Bordeaux"],
  GB: ["London", "Manchester", "Birmingham", "Glasgow", "Liverpool", "Bristol", "Edinburgh", "Leeds"],
  GR: ["Athens", "Thessaloniki", "Patras", "Heraklion", "Larissa"],
  IE: ["Dublin", "Cork", "Galway", "Limerick", "Waterford"],
  IN: ["Delhi", "Mumbai", "Bengaluru", "Chennai", "Hyderabad", "Pune", "Kolkata", "Kochi"],
  IT: ["Rome", "Milan", "Naples", "Turin", "Bologna", "Florence", "Venice", "Palermo"],
  JP: ["Tokyo", "Osaka", "Kyoto", "Yokohama", "Sapporo", "Fukuoka", "Nagoya", "Hiroshima"],
  MX: ["Mexico City", "Guadalajara", "Monterrey", "Cancun", "Merida"],
  NL: ["Amsterdam", "Rotterdam", "The Hague", "Utrecht", "Eindhoven", "Groningen", "Maastricht"],
  NO: ["Oslo", "Bergen", "Trondheim", "Stavanger", "Tromso", "Kristiansand", "Drammen"],
  NZ: ["Auckland", "Wellington", "Christchurch", "Hamilton", "Dunedin"],
  PL: ["Warsaw", "Krakow", "Gdansk", "Wroclaw", "Poznan", "Lodz", "Szczecin"],
  PT: ["Lisbon", "Porto", "Faro", "Coimbra", "Braga", "Funchal"],
  SA: ["Riyadh", "Jeddah", "Dammam", "Mecca", "Medina"],
  SE: ["Stockholm", "Gothenburg", "Malmo", "Uppsala", "Vasteras", "Orebro", "Linkoping", "Helsingborg"],
  SG: ["Singapore"],
  TR: ["Istanbul", "Ankara", "Izmir", "Antalya", "Bursa"],
  US: ["New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Miami", "Seattle", "Boston", "San Francisco", "Atlanta"],
  ZA: ["Johannesburg", "Cape Town", "Durban", "Pretoria", "Port Elizabeth"],
};

export const SAFE_ROUTE_CITY_QUERY_OVERRIDES = {
  GR: {
    Patras: "Patra",
  },
};
